spring:
  application:
    name: demo

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=studentinfo;integratedSecurity=true;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
